### ISSUE TITLE
Use as VSCode extension

### ISSUE THREAD

**Issue by fire** [rpetrich/deciduous#16]
As a person who uses VSCode and wants to version the graph.

I wanted to be able to preview graph changes in a window and also use standard version control tools to diagram.

**Comment by swagitda** [comment]
@fire great news, we just released a vs code extension: https://github.com/shortridge-sensemaking/deciduous-vscode (bonus [blog announcement](https://kellyshortridge.com/blog/posts/deciduous-for-vscode-local-decision-tree-editing/))

thanks again for submitting this as a request!
