### ISSUE TITLE
Accessibility: color blind friendliness

### ISSUE THREAD

**Issue by micahhausler** [rpetrich/deciduous#23]
I love the tool, but for folks who are red blind, the difference between attacks and mitigations can be difficult to tell the difference:
<img width="350" alt="Screen Shot 2022-01-26 at 11 09 45 AM" src="https://user-images.githubusercontent.com/791000/151200894-bc7b74be-ccae-4898-af49-5b856ec71eba.png">

vs

<img width="350" alt="Screen Shot 2022-01-26 at 10 33 55 AM" src="https://user-images.githubusercontent.com/791000/151200930-91b47868-060b-4825-bcc9-05798f67efbd.png">

I did a cursory web search, and entered the [current color values](https://davidmathlogic.com/colorblind/#%23F2AAD3-%23BFD5EF-%23580ABB-%23272727) to show how they render to different folks.
<img width="350" alt="Screen Shot 2022-01-26 at 11 17 27 AM" src="https://user-images.githubusercontent.com/791000/151202312-d04220ce-a2e5-42c5-9be7-663acf659d18.png"> 

That site also has good recommendations for accessible pallets. You could also consider using different shapes/corners to differentiate nodes in the graph

**Comment by swagitda** [comment]
@micahhausler the default colors were updated slightly for better accessibility and there's also now the ability to specify `theme: accessible` in the YAML to get an entirely different color scheme -- let us know your thoughts

**Comment by micahhausler** [comment]
Thanks for making the site accessible! Lgtm
