### ISSUE TITLE
Rename Reality option

### ISSUE THREAD

**Issue by briansebby** [rpetrich/deciduous#52]
I am using Deciduous for some slightly different types of flowcharts than intended, so I understand if this request is not accepted, but I was wondering if there might be an option added allowing you to rename the "Reality" box at the very top of the screen to something more specific to the flow being diagrammed.  In my case, I am using Deciduous to map out all of the security actions that our mail systems can take as a message flows through them, and it would be helpful if I could rename the top box to say "Incoming Email" or something similar.

**Comment by rpetrich** [comment]
`reality` can now be declared in the facts section, with any custom name.
